#!/bin/bash

# A POSIX variable
OPTIND=1         # Reset in case getopts has been used previously in the shell.

# Initialize our own variables:
deploy_env="DEV"

function show_help () {
    echo "Usage: ./deploy -e [DEV|PROD]"
}

while getopts "h?e:" opt; do
    case "$opt" in
    h|\?)
        show_help
        exit 0
        ;;
    e)  deploy_env=${OPTARG}
        ;;
    esac
done

if [ "$deploy_env" == "DEV" ] ; then
    GIN_MODE=debug go run src/server.go
elif [ "$deploy_env" == "PROD" ] ; then
    GIN_MODE=release go run src/server.go
else
    show_help
fi

# End
